// Auth
export const CREAR_USUARIO = 'CREAR_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DESACTIVATE_ERROR = 'DESACTIVATE_ERROR';

// Proyectos
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const ABRIR_MODAL = 'ABRIR_MODAL';
export const CREAR_PROYECTO = 'CREAR_PROYECTO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';

// Tasks
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const EDITAR_TAREA_MODAL = 'EDITAR_TAREA_MODAL';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const EDITAR_TAREA = 'EDITAR_TAREA';
export const LIMPIAR_LISTADO_DE_TAREAS = 'LIMPIAR_LISTADO_DE_TAREAS';

